//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryEntities : DbContext
    {
        public LibraryEntities()
            : base("name=LibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<books> books { get; set; }
        public virtual DbSet<chambers> chambers { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<fields> fields { get; set; }
        public virtual DbSet<formular> formular { get; set; }
        public virtual DbSet<interpretors> interpretors { get; set; }
        public virtual DbSet<quantity> quantity { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<storage> storage { get; set; }
        public virtual DbSet<trading> trading { get; set; }
    }
}
